@ECHO OFF
ECHO.
ECHO !!!ATTENTION!!!
ECHO.
ECHO THIS MUST BE EXTRACTED TO C:\DJGPP\ WITH DIRECTORY STRUCTURES INTACT
ECHO FOR THIS TO WORK!
ECHO.
ECHO.
ECHO SETTING PATH
set PATH=C:\DJGPP\BIN;%PATH%
ECHO.
ECHO SETTING ENVIRONMENT
set djgpp=c:\djgpp\djgpp.env
ECHO.
ECHO DONE!